### PR TITLE
Fix spelling and make instructions easier to read

### PR DESCRIPTION
**Pull request by violet-fish**
- Fixed spelling errors
- Slightly changed grammar and wording of steps to make them
easier to read
- Minor fixes to formatting

For all the changes in wording, feel free to keep the original wording if you feel it fits better with your writing tone. At the very least, updating the formatting to be consistent and fixing the spelling errors will make this build guide much easier to read.

### CODE REVIEW

**Comment by violet-fish** [comment]
The build guide is very good and well thought out. The pictures clearly illustrate all the steps so making the instructions mostly unnecessary.

**Comment by violet-fish** [comment]
Only other thing I noticed is the instructions for the reset switch seem a bit odd. I’m guessing the video classifies the instructions; but I can’t see how filling the through holes with solder before putting the switch in would make it easier to install

**Comment by barbellboards** [comment]
Thanks for grammar-checking the post!
This is what happens when I rush to get things in while working late at night :')

**Comment by barbellboards** [comment]
> Only other thing I noticed is the instructions for the reset switch seem a bit odd. I’m guessing the video classifies the instructions; but I can’t see how filling the through holes with solder before putting the switch in would make it easier to install

Yeah, the videos help a good bit. Trying to embed them into GitHub is not easy though

**Pull request merged**
